trigger:
- master

variables:
  AgentImage: 'ubuntu-latest'

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 'BuildJob'
    displayName: 'Serverless Build'
    pool:
      vmImage: $(AgentImage)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '>12.x.x'
      displayName: Install Node
    
    - bash: |
        npm install -no-cache
        npm install -g serverless
      displayName: Install Serverless Dependencies and Plugins
    
    - bash: |
        serverless package --package /tmp/sls_package/
        mv ./package.zip /tmp/sls_package
      displayName: Create package artifact
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: /tmp/sls_package
        artifactName: sls_package
      displayName: Publish serverless framework package artifact

- stage: 'Deploy_AWS_euc1'
  displayName: 'Deploy sls'
  dependsOn: ['Build']
  jobs:
  - job: 'DeployJob'
    displayName: 'Serverless Deployment to AWS'
    pool:
      vmImage: $(AgentImage)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '>12.x.x'
      displayName: Install Node
    
    - bash: |
        npm install -no-cache
        npm install -g serverless
      displayName: Install Serverless Dependencies and Plugins
      
    - download: current
      artifact: 'sls_package'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-default'
        regionName: 'eu-central-1'
        scriptType: 'inline'
        inlineScript: | 
          mv $(Pipeline.Workspace)/sls_package/package.zip .
          sls deploy --package $(Pipeline.Workspace)/sls_package
      displayName: Serverless framework deploy

